name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug
 # or run: ./gradlew assembleRelease

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: app/build/outputs
